### ISSUE TITLE
Squares generated with `classic` option slightly too large

### ISSUE THREAD

**Issue by jasperhabicht** [EagleoutIce/fancyqr#38]
It feels as if the squares that are generated using the `classic` option are a tad too large or maybe a stroke is drawn around them?

MWE:
```tex
\documentclass{article}
\usepackage{fancyqr}

\begin{document}
\fancyqr[color=black, classic]{https://www.google.com}
\end{document}
```
        
Note that this is especially (only?) visible when creating a relatively small QR code and zooming into it:

![image](https://github.com/user-attachments/assets/deb11237-edf8-4c68-ba37-6d61921b4093)

**Comment by EagleoutIce** [comment]
Oh thank you very much! I probably forgot to reduce the compensation for non-rounded squares and will get to it asap!
