### ISSUE TITLE
Broken example files 

### ISSUE THREAD

**Issue by GitHubSwimmer** [EagleoutIce/fancyqr#39]
pdflatex qr-minimal.tex
##########################################################
**! Package xkeyval Error: `classic' undefined in families `qr,fancyqr'.

See the xkeyval package documentation for explanation.**
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.10 \fancyqr[classic,padding]
                              {https://github.com/EagleoutIce/fancyqr}
........
###########################################################
pdflatex  qr-example.tex
###########################################################

! Package xkeyval Error: `size' undefined in families `qr,fancyqr'.

See the xkeyval package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.23 \fancyqrset{size=3.25cm, level=H, padding}
......

**Comment by GitHubSwimmer** [comment]
.....
! Package xkeyval Error: `random color' undefined in families `qr,fancyqr'.

See the xkeyval package documentation for explanation.
Type  H <return>  for immediate help.
.....

**Comment by EagleoutIce** [comment]
So the problem may be that you have an older installation from texlive which interferes with this repository. Could you please add the logfile lines related to the loading of `fancyqr`?

**Comment by GitHubSwimmer** [comment]
Dear Florian, this bug can be closed, it was a problem of usage the wrong fancyqr library
