### ISSUE TITLE
Error in the doc?

### ISSUE THREAD

**Issue by quark67** [EagleoutIce/fancyqr#43]
We read "six other styles" (line 48 of fancyqr-doc.tex). But I count 5:

1. `flat`
2. `frame`
3. `blobs`
4. `glitch`
5. `dots`

what is the 6th? The `default` style? 

If it's so, I suggest replacing:

```tex
At the moment, there are six other styles for the qr-code |flat|, |frame|, |blobs|, |glitch|, and |dots|,
that you can load (locally) by using |\FancyQrLoad{<name>}|. The default style is named |default| 
and can be 'reset' by |\FancyQrLoad{default}| or |\FancyQrLoadDefault|.
```

with:

```tex
At the moment, there are six other styles for the qr-code: |flat|, |frame|, |blobs|, |glitch|, and |dots|,
that you can load (locally) by using |\FancyQrLoad{<name>}|, and the default style, which is named |default|
and can be 'reset' by |\FancyQrLoad{default}| or |\FancyQrLoadDefault|.
```

(note the added `:` before the list of the 5 first styles, and that the `. The default style is` replaced by `, and the default style, which is`).

Also doesn't the surligned text be colored instead of black?
<img width="887" alt="image" src="https://github.com/user-attachments/assets/bede5117-ccdd-4d88-bcbf-1165a020b908">

If so, `\FancyQrDoNotPrintRadius` need to be added to the keywords in line 25 of fancyqr-doc.tex.

**Comment by EagleoutIce** [comment]
Thank you very much for the report, you are correct! I have addressed the documentation problems within the linked pull request :)

**Comment by quark67** [comment]
Thanks! I'm sorry that I have used a wrong word in my previous message, I have written "surligned" instead of "highlight" (because in French it's "surligné"). But you've understood what I mean. I close this issue.
